backend/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('schedules.urls')),
    path('reports/', include('reports.urls')),
]

backend/schedules/urls.py
from django.urls import path
from . import views

app_name = 'schedules'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('semester/', views.SemesterListView.as_view(), name='semester-list'),
    path('semester/new/', views.SemesterCreateView.as_view(), name='semester-create'),
    path('semester/<slug:semester_code>/', views.SemesterDetailView.as_view(), name='semester-detail'),
    path('semester/<slug:semester_code>/update/', views.SemesterUpdateView.as_view(), name='semester-update'),
    path('semester/<slug:semester_code>/delete/', views.SemesterDeleteView.as_view(), name='semester-delete'),

    path('semester/<slug:semester_code>/program/new/', views.ProgramCreateView.as_view(), name='program-create'),
    path('semester/<slug:semester_code>/program/<slug:program_code>/', views.ProgramDetailView.as_view(), name='program-detail'),
    path('semester/<slug:semester_code>/program/<slug:program_code>/update/', views.ProgramUpdateView.as_view(), name='program-update'),
    path('semester/<slug:semester_code>/program/<slug:program_code>/delete/', views.ProgramDeleteView.as_view(), name='program-delete'),


    path('semester/<slug:semester_code>/program/<slug:program_code>/course/new/', views.CourseCreateView.as_view(), name='course-create'),
    path('semester/<slug:semester_code>/program/<slug:program_code>/course/<int:course_id>/', views.CourseDetailView.as_view(), name='course-detail'),
    path('semester/<slug:semester_code>/program/<slug:program_code>/course/<int:course_id>/update/', views.CourseUpdateView.as_view(), name='course-update'),
    path('semester/<slug:semester_code>/program/<slug:program_code>/course/<int:course_id>/delete/', views.CourseDeleteView.as_view(), name='course-delete'),


    path('semester/<slug:semester_code>/program/<slug:program_code>/course/<int:course_id>/session/new/', views.CourseSessionCreateView.as_view(), name='course-session-create'),
    path('semester/<slug:semester_code>/program/<slug:program_code>/course/<int:course_id>/session/<int:session_id>/update/', views.CourseSessionUpdateView.as_view(), name='course-session-update'),
    path('semester/<slug:semester_code>/program/<slug:program_code>/course/<int:course_id>/session/<int:session_id>/delete/', views.CourseSessionDeleteView.as_view(), name='course-session-delete'),



    path('semester/<slug:semester_code>/program/<slug:program_code>/schedule/', views.ProgramSchedule.as_view(), name='program-schedule'),




    #path('semester/<slug:semester_code>/add-new-program', views.create_program, name='program-create'),
    #path('program/<slug:code>', views.ProgramDetailView.as_view(), name='program-detail'),


    path('instructor/new/', views.InstructorCreateView.as_view(), name='instructor-create'),
    path('instructor/', views.InstructorListView.as_view(), name='instructor-list'),
    path('instructor/<int:pk>/update/', views.InstructorUpdateView.as_view(), name='instructor-update'),
    path('instructor/<int:pk>/delete/', views.InstructorDeleteView.as_view(), name='instructor-delete'),
    path('course-title/new/', views.CourseTitleCreateView.as_view(), name='course-title-create'),
    path('course-title/', views.CourseTitleListView.as_view(), name='course-title-list'),
    path('program-title/', views.ProgramTitleListView.as_view(), name='program-title-list'),
    path('program-title/<int:pk>/update/', views.ProgramTitleUpdateView.as_view(), name='program-title-update'),
    path('program-title/<int:pk>/delete/', views.ProgramTitleDeleteView.as_view(), name='program-title-delete'),
    path('program-title/new/', views.ProgramTitleCreateView.as_view(), name='program-title-create'),



    path('export-data/', views.ExportDataTemplateView.as_view(), name='export-data'),
    path('export-data/excel/', views.export_data_to_excel, name='export-data-to-excel'),
    #path('import-data')
    #path('spreadsheet/upload/')
]

backend/schedules/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

class Instructor(models.Model):
    first_name = models.CharField(verbose_name='نام', max_length=30)
    last_name = models.CharField(verbose_name='نام خانوادگی', max_length=30)

    def __str__(self) -> str:
        return f'{self.first_name} {self.last_name}'

class ProgramTitle(models.Model):
    title = models.CharField(verbose_name='عنوان', unique=True, max_length=80)

    def __str__(self) -> str:
        return self.title

class CourseTitle(models.Model):
    title = models.CharField(verbose_name='عنوان', unique=True, max_length=80)

    def __str__(self) -> str:
        return self.title

# ترم
class Semester(models.Model):

    MONTH_CHOICES = {
        1:'فروردین',
        2:'اردیبهشت',
        3:'خرداد',
        4:'تیر',
        5:'مرداد',
        6:'شهریور',
        7:'مهر',
        8:'آبان',
        9:'آذر',
        10:'دی', 
        11:'بهمن', 
        12:'اسفند',
    }
    year_validators = [MinValueValidator(1390), MaxValueValidator(1450)]
    day_validator = [MinValueValidator(1), MaxValueValidator(31)]
    code = models.SlugField('کد', max_length=20)
    day_start = models.IntegerField(verbose_name='روز شروع', validators=day_validator)
    month_start = models.PositiveSmallIntegerField(verbose_name='ماه شروع', choices=MONTH_CHOICES)
    year_start = models.IntegerField(verbose_name='سال شروع', validators=year_validators)
    day_end = models.IntegerField(verbose_name='روز پایان', validators=day_validator)
    month_end = models.PositiveSmallIntegerField(verbose_name='ماه پایان' ,choices=MONTH_CHOICES)
    year_end = models.IntegerField(verbose_name='سال پایان', validators=year_validators)


    def __str__(self) -> str:
        return self.code
    
    class Meta:
        ordering = ['year_start', 'month_start']

# دوره
class Program(models.Model):
    code = models.SlugField(verbose_name='کد', max_length=20, unique=True)
    title = models.ForeignKey(verbose_name='عنوان', to=ProgramTitle, on_delete=models.SET_NULL, null=True, blank=True)
    semester = models.ForeignKey(verbose_name='ترم', to=Semester, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.code
    
    
# درس
class Course(models.Model):
    title= models.ForeignKey(verbose_name='عنوان', to=CourseTitle, on_delete=models.CASCADE)
    instructor = models.ForeignKey(verbose_name='مدرس', to=Instructor, on_delete=models.SET_NULL, null=True, blank=True)
    program = models.ForeignKey(verbose_name='دوره', to=Program, on_delete=models.CASCADE)
    instructor_evaluation_grade = models.IntegerField(verbose_name='نمره ارزیابی مدرس', validators=[MinValueValidator(1), MaxValueValidator(5)], null=True, blank=True)
    group = models.SmallIntegerField(verbose_name='گروه', validators=[MinValueValidator(1)], null=True, blank=True)


    def __str__(self) -> str:
        return self.title.title

class CourseSession(models.Model):
    WEEKDAY_CHOICES = [
        ('ش', 'شنبه'),
        ('ی', 'یک‌شنبه'),
        ('د', 'دوشنبه'),
        ('س', 'سه‌شنبه'),
        ('چ', 'چهارشنبه'),
        ('پ', 'پنج‌شنبه'),
        ('ج', 'جمعه'),
    ]

    course = models.ForeignKey(verbose_name='درس', to=Course, on_delete=models.CASCADE)
    location = models.CharField(verbose_name='محل برگزاری', max_length=50, null=True, blank=True)
    start_time = models.TimeField(verbose_name='ساعت شروع')
    end_time = models.TimeField(verbose_name='ساعت پایان')
    weekday = models.CharField(verbose_name='روز هفته', max_length=1, choices=WEEKDAY_CHOICES)

    def duration_in_minutes(self):
        start_minutes = self.start_time.hour*60 + self.start_time.minute
        end_minutes = self. end_time.hour*60 + self.end_time.minute
        return end_minutes - start_minutes
    

    def duration_in_seconds(self):
        start_seconds = self.start_time.hour * 3600 + self.start_time.minute * 60
        end_seconds = self.end_time.hour * 3600 + self.end_time.minute * 60
        return end_seconds - start_seconds

    def schedule_session_width(self):
        return f'{self.duration_in_seconds()/40}px'


    def starting_point(self):
        return f'{((self.start_time.hour * 3600 + self.start_time.minute * 60)/40)-600}px'

backend/schedules/forms.py
from django import forms
from .models import Course, Semester

class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ['title', 'instructor', 'group', 'instructor_evaluation_grade']
        widgets = {
            'instructor_evaluation_grade': forms.NumberInput(attrs={
                'min': 1,
                'max': 5,
            }),
            'group': forms.NumberInput(attrs={
                'min': 1,
                'max': 10,
            }),
        }


class SemesterForm(forms.ModelForm):
    class Meta:
        model = Semester
        fields = ['code', 'day_start', 'month_start', 'year_start', 'day_end', 'month_end', 'year_end']
        widgets = {
            'day_start': forms.NumberInput(attrs={
                'min': 1,
                'max': 31,
            }),
            'day_end': forms.NumberInput(attrs={
                'min': 1,
                'max': 31,
            }),
            'year_start': forms.NumberInput(attrs={
                'min': 1390,
                'max': 1450,
            }),
            'year_end': forms.NumberInput(attrs={
                'min': 1390,
                'max': 1450,
            }),
        }

backend/schedules/templates/schedules/course_confirm_delete.html
{% extends 'base/base.html' %}
{% load static %}

{% block link %}
    <link rel="stylesheet" href="{% static '/styles/form.css' %}">
{% endblock link %}

{% block content %}

    <div style="display: flex; flex-direction: column; justify-content: center; align-items: center; gap: 2rem; margin-bottom: 3rem; font-size: 1.5rem;">
        <p>آیا از حذف درس  {{ object }} {% if object.group %}(گروه {{ object.group }}){% endif %} اطمینان دارید؟</p>
        <p style="color: #ff0000;">توجه: با حذف این درس، تمامی اطلاعات مرتبط با آن (جلسات هفتگی، نمره ارزیابی استاد و ...) حذف خواهند شد.</p>
    </div>
    <div class="delete-form">
        <form method="post">
            {% csrf_token %}
            {{ form }}
            <div style="display: flex; gap: 2rem; justify-content: center; align-items: center;">
                <input type="submit" value="تایید">
                <a href="{% url 'schedules:course-detail' semester_code=object.program.semester program_code=object.program.code course_id=object.id %}" class="cancel-btn">
                        انصراف
                </a>    
            </div>
        </form>    
    </div>
{% endblock content %}

backend/schedules/templates/schedules/course_detail.html
{% extends 'base/base.html' %}

{% block content %}




<h3 style="text-align: center; font-size: 1.5rem; margin-bottom: 1.2rem;">
     اطلاعات درس
     <a href="{% url 'schedules:course-update' semester_code=course.program.semester program_code=course.program course_id=course.id %}" style="font-size: .9rem; text-decoration: none; color: #0032d8;">
        (ویرایش اطلاعات)
    </a>
</h3>
    {% with sessions=course.coursesession_set.all %}
        <div dir="rtl" style="display: flex; flex-direction: column; gap: .7em; font-size: 1.3rem; text-align: center; margin-bottom: 2rem;">
            <p>عنوان درس: {{ course.title }} {% if course.group %}(<span style="color: #ff1d1d;">گروه {{ course.group }}</span>){% endif %}</p>
            <p>
                دوره:
                <a href="{% url 'schedules:program-detail' semester_code=course.program.semester program_code=course.program %}" style="text-decoration: none; color: #0032d8;">
                    {{ course.program }}
                </a>
            </p>
            <p>مدرس: {{ course.instructor }}</p>
            <p>نمره ارزیابی مدرس: {% if course.instructor_evaluation_grade %}{{course.instructor_evaluation_grade}}{% else %}ثبت نشده{%endif%}</p>
            <p>تعداد جلسات هفتگی: {{ sessions|length }} جلسه</p>
        </div>

        {% if sessions %}
            <div style="display: flex; align-items: center; gap: 1rem; margin-bottom: 1rem;">
                <h3 style="font-size: 1.2rem;">لیست جلسات هفتگی:</h3>
                <a href="{% url 'schedules:course-session-create' semester_code=course.program.semester program_code=course.program course_id=course.id %}" style="text-decoration: none; color: #0032d8;">
                    افزودن جلسه‌ی درسی جدید
                </a>           
            </div>
            <div style="display: flex; gap: 4rem; flex-wrap: wrap;">
                {% for session in sessions %}
                    <div style="display: flex; flex-direction: column;">
                        <div style="background-color: #c7d4ff; display: flex; flex-direction: column; gap: 8px; padding: 1em; width: 12em; text-align: center; font-size: 1.2rem; border-top-left-radius: 5px; border-top-right-radius: 5px;">
                            <p>روز: {{ session.get_weekday_display }}</p>
                            <p>ساعت شروع: {{ session.start_time|date:'H:i' }}</p>
                            <p>ساعت پایان: {{ session.end_time|date:'H:i' }}</p>
                            <p>مکان: {{ session.location }}</p>
                        </div>
                        <div style="display: grid; grid-template-columns: 1fr 1fr;">
                            <a href="{% url 'schedules:course-session-delete' semester_code=course.program.semester program_code=course.program course_id=course.id session_id=session.id %}" style="background-color: #ff1d1d; padding: 1rem; text-decoration: none; color: #f1f1f1; text-align: center; font-weight: bold;">
                                حذف
                            </a>        
                            <a href="{% url 'schedules:course-session-update' semester_code=course.program.semester program_code=course.program course_id=course.id session_id=session.id %}" style="background-color: #ffee55; padding: 1rem; text-decoration: none; color: rgb(36, 36, 36); text-align: center; font-weight: bold;">
                                ویرایش
                            </a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <h3 style="font-size: 1.5em; text-align: center;" dir="rtl">برای این درس، جلسه‌ای ثبت نشده است. <a href="{% url 'schedules:course-session-create' semester_code=course.program.semester program_code=course.program course_id=course.id %}" style="text-decoration: none; color: #0032d8;">افزودن جلسه‌ی درسی جدید</a></h3>
        {% endif %}
    {% endwith %}
{% endblock content %}

backend/schedules/templates/schedules/course_session_confirm_delete.html
{% extends 'base/base.html' %}
{% load static %}

{% block link %}
    <link rel="stylesheet" href="{% static '/styles/form.css' %}">
{% endblock link %}

{% block content %}

    <div style="display: flex; flex-direction: column; justify-content: center; align-items: center; gap: 2rem; margin-bottom: 3rem; font-size: 1.5rem;">
        <p>آیا از حذف جلسه هفتگی  {{ object.course }} {% if object.course.group %}(گروه {{ object.course.group }}){% endif %} اطمینان دارید؟</p>
    </div>
    <div class="delete-form">
        <form method="post">
            {% csrf_token %}
            {{ form }}
            <div style="display: flex; gap: 2rem; justify-content: center; align-items: center;">
                <input type="submit" value="تایید">
                <a href="{% url 'schedules:course-detail' semester_code=object.course.program.semester program_code=object.course.program.code course_id=object.course.id %}" class="cancel-btn">
                        انصراف
                </a>    
            </div>
        </form>    
    </div>
{% endblock content %}

backend/schedules/templates/schedules/course_session_update_form.html
{% extends 'base/base.html' %}
{% load static %}

{% block link %}
    <link rel="stylesheet" href="{% static 'styles/update_form.css' %}">
{% endblock link %}


{% block content %}
    <h2 style="font-size: 1.5rem; margin-bottom: 4rem; text-align: center;">
        پس از اعمال تغییرات، "به‌روزرسانی" را انتخاب کنید
    </h2>
    <div class="update-form">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="به‌روزرسانی">
            </form>        
        </div>
{% endblock content %}

backend/schedules/templates/schedules/course_title_list.html
{% extends 'base/base.html' %}
{% load static %}


{% block link %}
    <link rel="stylesheet" href="{% static '/styles/semester_list.css' %}">
{% endblock link %}

{% block content %}
    {% if object_list %}
        <div class="new-semester" style="text-align: left;">
            <a href="{% url 'schedules:course-title-create' %}" class="new-semester">عنوان درس جدید</a>
        </div>
        <div style="text-align: right; margin-bottom: 2rem; font-size: 1.5rem;">
            <h2>عناوین دروس:</h2>
        </div>
        <div style="display: flex; flex-direction: column; gap: 1rem;">
            {% for course_title in object_list %}
                <p style="font-size: 1.2rem;">
                    {{ course_title.title }}
                </p>
            {% endfor %}
        </div>
    {% else %}
        <div style="font-size: 1.7em; text-align: center;">
            عنوان درسی ثبت نشده است.
            <a href="{% url 'schedules:course-title-create' %}" style="text-decoration: none; color: #0032d8;">
                عنوان درس جدید
            </a>
        </div>
    {% endif %}
{% endblock content %}

backend/schedules/templates/schedules/export_data.html
{% extends 'base/base.html' %}
{% load svg %}

{% block content %}
<div style="display: flex; flex-direction: column; align-items: center;">
    <a href="{% url 'schedules:export-data-to-excel' %}" style="display: inline-block; text-decoration: none; color: #000;">
        <div style="display: flex; flex-direction: column;">
            {% svg 'microsoft-excel-icon' %}
            <div>
                Excel
            </div>
        </div>
    </a>
</div>
{% endblock content %}

backend/schedules/templates/schedules/index.html
{% extends 'base/base.html' %}
{% load static %}
{% load svg %}

{% block content %}
    <div style="display: flex; flex-direction: column; gap: 4rem; align-items: center;">
        <a href="{% url 'schedules:semester-list' %}" style="width: 15rem; display: flex; justify-content: center; align-items: center; gap: 1rem; font-size: 2.5rem; text-decoration: none; background-color: rgb(147, 255, 165); color: #000; padding-inline: 4rem; padding-block: 2rem; border-radius: 5px;">
            <div>
                انتخاب ترم
            </div>
            {% svg 'check-mark-box-icon' %}
        </a>
        <a href="{% url 'schedules:export-data' %}" style="width: 15rem; display: flex; justify-content: center; align-items: center; gap: 1rem; font-size: 2.5rem; text-decoration: none; background-color: rgb(147, 203, 255); color: #000; padding-inline: 4rem; padding-block: 2rem; border-radius: 5px;">
            <div>
                دریافت اطلاعات
            </div>
            {% svg 'cloud-download-icon' %}
        </a>
        <a href="" style="width: 15rem; display: flex; justify-content: center; align-items: center; gap: 1rem; font-size: 2.5rem; text-decoration: none; background-color: rgb(255, 235, 147); color: #000; padding-inline: 4rem; padding-block: 2rem; border-radius: 5px;">
            <div>
                بارگزاری اطلاعات
            </div>
            {% svg 'database-upload-icon' %}
        </a>
    </div>
{% endblock content %}

backend/schedules/templates/schedules/instructor_form.html
{% extends 'base/base.html' %}
{% load static %}


{% block link %}
    <link rel="stylesheet" href="{% static 'styles/form.css' %}">
{% endblock link %}

{% block content %}
<h2 style="font-size: 1.5rem; margin-bottom: 4rem; text-align: center;">پس از وارد کردن اطلاعات استاد، "ذخیره" را انتخاب کنید</h2>
<div class="form" dir="rtl">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="ذخیره">
    </form>    
</div>
{% endblock content %}

backend/schedules/templates/schedules/instructor_update_form.html
{% extends 'base/base.html' %}
{% load static %}


{% block link %}
    <link rel="stylesheet" href="{% static 'styles/update_form.css' %}">
{% endblock link %}

{% block content %}
    <h2 style="font-size: 1.5rem; margin-bottom: 4rem; text-align: center;">
        پس از اعمال تغییرات، "به‌روزرسانی" را انتخاب کنید
    </h2>
    <div class="update-form" dir="rtl">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="به‌روزرسانی">
        </form>    
    </div>
{% endblock content %}

backend/schedules/templates/schedules/program_title_list.html
{% extends 'base/base.html' %}

{% block content %}
<a href="{% url 'schedules:program-title-create' %}" style="text-decoration: none; font-size: 1.5rem; display: block; text-align: center; margin-bottom: 3rem;">
    <div style="background-color: rgb(0, 11, 77); color: #f1f1f1; width: 15rem; padding: 1rem; border-radius: 5px; margin-inline: auto;">
        افزودن عنوان دوره جدید
    </div>
</a>

    {% if object_list %}
        <div style="display: flex; flex-direction: column; gap: 4rem; align-items: center;">
            {% for program_title in object_list %}
            <div style="display: flex; align-items: center; gap: 3rem;">
                <p style="font-size: 1.5rem;">{{ program_title.title }}</p>
                <div style="display: flex; gap: 1rem; font-size: 1.1rem; text-decoration: none;">
                    <a href="{% url 'schedules:program-title-delete' program_title.id %}" style="text-decoration: none;">حذف</a>
                    <a href="{% url 'schedules:program-title-update' program_title.id %}" style="text-decoration: none;">ویرایش</a>
                </div>
            </div>
            {% endfor %}
        </div>
    {% else %}
        <p dir="rtl" style="text-align: center; font-size: 1.5rem;">عنوانی ثبت نشده است.</p>
    {% endif %}

{% endblock content %}

backend/schedules/templates/schedules/program_update_form.html
{% extends 'base/base.html' %}
{% load static %}

{% block link %}
    <link rel="stylesheet" href="{% static 'styles/update_form.css' %}">
{% endblock link %}

{% block content %}
<div class="update-form" dir="rtl">
    <h2 style="font-size: 1.5rem; margin-bottom: 4rem; text-align: center;">پس از اعمال تغییرات، "به‌روزرسانی" را انتخاب کنید</h2>

    <form method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="به‌روزرسانی">
    </form>    
</div>

<a href="{% url 'schedules:program-delete' semester_code=program.semester program_code=program.code %}" style="text-decoration: none; color: #f1f1f1; position: absolute; top: 0; left: 0; display: inline-block;">
    <div style="background-color: #ff0000; padding-inline: 2rem; padding-block: .5rem; border-radius: 5px;">
        حذف دوره
    </div>
</a>

{% endblock content %}

backend/schedules/templates/schedules/semester_confirm_delete.html
{% extends 'base/base.html' %}
{% load static %}

{% block link %}
    <link rel="stylesheet" href="{% static '/styles/form.css' %}">
{% endblock link %}

{% block content %}

    <div style="display: flex; flex-direction: column; justify-content: center; align-items: center; gap: 2rem; margin-bottom: 3rem; font-size: 1.5rem;">
        <p>آیا از حذف ترم "{{ object.code }}" اطمینان دارید؟</p>
        <p style="color: #ff0000;">توجه: با حذف یک ترم، اطلاعات دوره‌ها و درس‌های آن ترم نیز حذف خواهند شد.</p>
    </div>
    <div class="delete-form">
        <form method="post">
            {% csrf_token %}
            {{ form }}
            <div style="display: flex; gap: 2rem; justify-content: center; align-items: center;">
                <input type="submit" value="تایید">
                <a href="{% url 'schedules:semester-detail' semester_code=object.code %}" class="cancel-btn">
                        انصراف
                </a>    
            </div>
        </form>    
    </div>
{% endblock content %}

backend/schedules/templates/schedules/semester_form.html
{% extends 'base/base.html' %}
{% load static %}

{% block link %}
    <link rel="stylesheet" href="{% static 'styles/form.css' %}">
{% endblock link %}

{% block content %}

<h2 style="font-size: 1.5rem; margin-bottom: 4rem; text-align: center;">پس از وارد کردن اطلاعات ترم، "ذخیره" را انتخاب کنید</h2>

<div class="form" dir="rtl">
    <form method="post">
        {% csrf_token %}
        <p>
            <label for="id_code">{{ form.code.label }}:</label>
            {{ form.code }}
        </p>
        <div style="display: flex; align-items: center; gap: 2rem;">
            <p>
                <label for="id_day_start">{{ form.day_start.label }}:</label>
                {{ form.day_start }}    
            </p>
            <p>
                <label for="id_month_start">{{ form.month_start.label }}:</label>
                {{ form.month_start }}    
            </p>
            <p>
                <label for="id_year_start">{{ form.year_start.label }}:</label>
                {{ form.year_start }}    
            </p>    
        </div>
        <div style="display: flex; align-items: center; gap: 2rem;">
            <p>
                <label for="id_day_end">{{ form.day_end.label }}:</label>
                {{ form.day_end }}    
            </p>
            <p>
                <label for="id_month_end">{{ form.month_end.label }}:</label>
                {{ form.month_end }}    
            </p>
            <p>
                <label for="id_year_end">{{ form.year_end.label }}:</label>
                {{ form.year_end }}    
            </p>
        </div>
        <input type="submit" value="ذخیره">
    </form>    
</div>
{% endblock content %}

backend/schedules/templates/schedules/semester_list.html
{% extends 'base/base.html' %}
{% load static %}


{% block link %}
    <link rel="stylesheet" href="{% static '/styles/semester_list.css' %}">
{% endblock link %}

{% block content %}
    {% if object_list %}
        <div class="new-semester" style="text-align: left;">
            <a href="{% url 'schedules:semester-create' %}" class="new-semester">ایجاد ترم جدید</a>
        </div>
        <div style="text-align: right; margin-bottom: 2rem; font-size: 1.4rem;">
            <h2>ترم مورد نظر را انتخاب کنید.</h2>
        </div>
        <div class="semester-list">
            {% for semester in object_list %}
                <a href="{% url 'schedules:semester-detail' semester.code %}" class="semester-link">
                    <div class="semester-card">
                        {{ semester.code }}
                    </div>
                </a>
            {% endfor %}
        </div>
    {% else %}
        <div style="font-size: 1.7em; text-align: center;">
            ترمی ثبت نشده است.
            <a href="{% url 'schedules:semester-create' %}" style="text-decoration: none; color: #0032d8;">
                ایجاد ترم جدید
            </a>
        </div>
    {% endif %}
{% endblock content %}