backend/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('schedules.urls')),
    path('reports/', include('reports.urls')),
]

backend/reports/urls.py
from django.urls import path
from . import views

app_name = 'reports'

urlpatterns = [
    path('revenue/', views.RevenueView.as_view(), name='revenue'),
    path('revenue/update/', views.RevenueFileUpdateView.as_view(), name='revenue-file-update'),
]

backend/reports/models.py
from django.db import models

# Create your models here.

backend/reports/views.py
from django.shortcuts import render, redirect
from django.views import View
import pandas as pd
import os
from .storage import OverwriteStorage

class RevenueView(View):
    def get(self, request, *args, **kwargs):
        context = {}
        revenue_file_name = 'reports/revenue_report/revenue_report.xlsx'
        if os.path.isfile(revenue_file_name):
            df = pd.read_excel(revenue_file_name)
            df = df[[ 'نام خانوادگي مدرس',
                    'کد دوره',
                    'ثبت نام شده',
                    'کل ساعات',
                    'شماره قرارداد',
                    'نوع دوره',
                    'مسئول دوره',
                    'کل مبلغ',
                    'عنوان دسته بندي دوره',
                    'تاريخ شروع دوره',
                    'تاريخ پايان دوره'
            ]]
            df = df.rename(columns={
                                'نام خانوادگي مدرس': 'مدرس',
                                'عنوان دسته بندي دوره': 'دسته‌بندی دوره',
                                'شماره قرارداد': 'مشتری',
                        })
            df['نفر ساعت'] = df['ثبت نام شده'].multiply(df['کل ساعات'])
            revenue_charts = [
                    {
                        'title': title,
                        'chart':
                        df.groupby([title]).agg({
                            'کل مبلغ': 'sum',
                            'کل ساعات': 'sum',
                            'ثبت نام شده': 'sum',
                            'نفر ساعت': 'sum',
                            'کد دوره': 'count'
                            }).reset_index().rename(columns={
                                'کد دوره': 'تعداد دوره',
                                'کل ساعات': 'مجموع ساعت‌ها',
                                'ثبت نام شده': 'مجموع ثبت‌نام کننده',
                                'نفر ساعت': 'مجموع نفر-ساعت'
                        })
                    }
                for title in  ['مسئول دوره', 'نوع دوره', 'دسته‌بندی دوره', 'مدرس', 'مشتری']
            ]
            '''
            revenue_charts.append(
                    df.agg({
                        'کل مبلغ': 'sum',
                        'کل ساعات': 'sum',
                        'ثبت نام شده': 'sum',
                        'کد دوره': 'count'
                        }).reset_index().rename(columns={
                            'کد دوره': 'تعداد دوره',
                            'کل ساعات': 'مجموع ساعت‌ها',
                            'ثبت نام شده': 'مجموع ثبت‌نام کننده',
                        })
            )
            '''
            for index, revenue_chart in enumerate(revenue_charts):
                revenue_chart['chart']['کل مبلغ'] = revenue_chart['chart']['کل مبلغ'].astype('int64')
                revenue_chart['chart']['مجموع ثبت‌نام کننده'] = revenue_chart['chart']['مجموع ثبت‌نام کننده'].astype('int64')
                revenue_chart['chart']['تعداد دوره'] = revenue_chart['chart']['تعداد دوره'].astype('int64')
                revenue_chart['chart']['مجموع نفر-ساعت'] = revenue_chart['chart']['مجموع نفر-ساعت'].astype('int64')
                revenue_chart['chart']['کل مبلغ'] = revenue_chart['chart']['کل مبلغ'].apply('{:,}'.format)
                revenue_chart['chart']['تعداد دوره'] = revenue_chart['chart']['تعداد دوره'].apply('{:,}'.format)
                revenue_chart['chart']['مجموع ثبت‌نام کننده'] = revenue_chart['chart']['مجموع ثبت‌نام کننده'].apply('{:,}'.format)
                revenue_chart['chart']['مجموع نفر-ساعت'] = revenue_chart['chart']['مجموع نفر-ساعت'].apply('{:,}'.format)
                revenue_charts[index]['chart'] = revenue_chart['chart'].to_html()
                
            context = {
                'revenue_charts': revenue_charts
            }
        return render(request, 'reports/revenue.html', context)
    

class RevenueFileUpdateView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'reports/revenue_file_update.html')
    def post(self, request, *args, **kwargs):
        excel_file = request.FILES['excel_file']
        OverwriteStorage(location='reports/revenue_report').save('revenue_report.xlsx', excel_file)
        return redirect('reports:revenue')

backend/reports/templates/reports/revenue.html
{% extends 'base/base.html' %}
{% load static %}
{% block link %}
    <link rel="stylesheet" href="{% static 'styles/revenue.css' %}">
{% endblock link %}
{% block content %}
    <a href="{% url 'reports:revenue-file-update' %}">
        <div style="position: absolute; right: 0; font-size: 1.2rem; padding-inline: 2rem; padding-block: 1rem; background-color: rgb(0, 87, 95); color: #f1f1f1; border-radius: 5px; cursor: pointer;">به‌روزرسانی فایل</div>
    </a>
    <div style="display: flex; flex-direction: column; gap: 2rem; align-items: center;">
        <h2 style="font-size: 1.5rem;">گزارش عملکرد</h2>
        <ul class="chart-navigation-bar" style="display: flex; justify-content: center;">
            {% for data in revenue_charts %}
                <li data-chart-variable="{{ data.title }}" style="padding: 2rem; font-size: 1.2rem; min-width: 4rem; text-align: center; cursor: pointer;">{{ data.title }}</li>
            {% endfor %}
        </ul>
        {% if revenue_charts %}
            {% for data in revenue_charts %}
                <div class="chart">
                    <div data-chart-variable="{{ data.title }}" style="display: none;">
                        {{ data.chart|safe }}
                    </div>
                </div>
            {% endfor %}
        {% endif %}
    </div>
{% endblock content %}

{% block script %}
    <script src="{% static 'scripts/revenue_charts.js' %}"></script>
{% endblock script %}

backend/reports/templates/reports/revenue_file_update.html
{% extends 'base/base.html' %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" accept=".xlsx" name="excel_file">
        <button type="submit">Import</button>
    </form>
{% endblock content %}